package main

import (
	"context"
	"fmt"
	"log"
	"net/http"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

func main() {
	// 1. Create the MCP Server instance
	s := server.NewMCPServer(
		"hello-go-mcp",
		"1.0.0",
	)

	// 2. Define and add the "hello" tool
	// This creates the {name: value} argument schema automatically
	tool := mcp.NewTool("hello",
		mcp.WithDescription("Says hello to a user"),
		mcp.WithString("name",
			mcp.Required(),
			mcp.Description("The name of the person to greet"),
		),
	)

	// Register the handler for the tool
	s.AddTool(tool, func(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		name, _ := request.RequireString("name")
		message := fmt.Sprintf("Hello, %s! (Greetings from the MCP Tool)", name)
		return mcp.NewToolResultText(message), nil
	})

	// 3. Set up the Streamable HTTP Transport
	// The session ID is generated by the SDK on first initialize
	streamableServer := server.NewStreamableHTTPServer(s, server.WithEndpointPath("/mcp"))

	mux := http.NewServeMux()

	// MCP Endpoint: Streamable HTTP (supports SSE streaming)
	mux.Handle("/mcp", streamableServer)

	// REST API Endpoint: Standard query param style
	mux.HandleFunc("/api/hello", func(w http.ResponseWriter, r *http.Request) {
		name := r.URL.Query().Get("name")
		if name == "" {
			name = "Stranger"
		}
		w.Header().Set("Content-Type", "text/plain")
		fmt.Fprintf(w, "Hello, %s! (Greetings from the REST API)", name)
	})

	// 4. Start the server
	fmt.Println("Server running at http://localhost:7881")
	fmt.Println("   - MCP Streamable HTTP: /mcp")
	fmt.Println("   - REST API:            /api/hello?name=value")

	if err := http.ListenAndServe(":7881", mux); err != nil {
		log.Fatalf("Server failed: %v", err)
	}
}
